//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleCond
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_APARTAMENTO
    {
        public int id { get; set; }
        public string numero_apto { get; set; }
        public string qtd_moradores { get; set; }
        public string bloco { get; set; }
    }
}
