//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleCond
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BLOCO
    {
        public int id { get; set; }
        public string numero_bloco { get; set; }
        public string qtd_apartamentos { get; set; }
        public string qtd_andar { get; set; }
        public string total_moradores { get; set; }
    }
}
