//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleCond
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_COND
    {
        public int id { get; set; }
        public string nome_cond { get; set; }
        public string area_terreno { get; set; }
        public string blocos { get; set; }
        public string unida_andar { get; set; }
        public string apartamentos { get; set; }
        public string area_apartamento { get; set; }
        public string vagas { get; set; }
    }
}
